x-defaults:
  x-postgres-healthcheck: &x-postgres-healthcheck 
    healthcheck: 
      test: ["CMD-SHELL", "pg_is_ready -U postgres -h localhost"]
      interval: 5s 
      timeout: 5s 
      retries: 20 

services:
  # ----- infra -----
  kafka:
    container_name: "kafka"
    image: bitnami/kafka:latest 
    env_file: ./infra/env/.kafka.env
    volumes:
      - kafka-data:/bitname/kafka 
    ports:
      - 29092:29092
      - 9092:9092
    healthcheck:
      test: ["CMD-SHELL", "/opt/bitnami/kafka/bin/kafka-topics/sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1 || exit 1"]
      interval: 10s 
      timeout: 5s 
      retries: 10 

  kafka-ui:
    container_name: kafka-ui 
    image: provectuslabs/kafka-ui:latest 
    env_file: ./infra/env/.kafka_ui.env
    ports: 
      - 8081:8080 
    depends_on:
      kafka:
        condition: service_healthy

  redis:
    container_name: redis 
    image: redis:7
    ports: ["6379:6379"]
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s 
      timeout: 3s 
      retries: 20 

  mailhog:
    image: mailhog/mailhog:latest 
    container_name: mailhog 
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI 

  gateway: 
    container_name: "gateway"
    image: traefik:v3.5.2
    command: ["--api.insecure=true", "--providers.docker=true", "--entrypoints.web.address=:80"]
    ports:
      - 80:80 
      - 8080:8080
    depends_on: [catalog, orders, payments, notifications]

  prometheus:
    image: prom/prometheus:v2.53.1
    container_name: prometheus 
    command: [
      "--config.file=/etc/prometheus/prometheus.yml",
      "--storage.tsdb.retention.time=15d",
    ]
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro 
      - prometheus_data:/prometheus 
    ports:
      - "9090:9090"
    restart: unless-stopped
  
  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana 
    environment: 
      - GF_SECURITY_ADMIN_USER=admin 
      - GF_SECURITY_ADMIN_PASSWORD=admin 
    volumes:
      - grafana_data:/var/lib/grafana 
      - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro 
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki 

  loki:
    image: grafana/loki:main-37eddab
    container_name: loki 
    command: ["-config.file=/etc/loki/local-config.yml", "-validation.allow-structured-metadata=false"]
    ports:
      - "3100:3100"
    volumes:
      - ./infra/loki/local-config.yml:/etc/loki/local-config.yml:ro 
      - loki_data:/loki 
    restart: unless-stopped

  promtail:
    image: grafana/promtail:main-37eddab
    container_name: promtail
    command: ["-config.file=/etc/promtail/config.yml"]
    volumes:
      - /var/log:/var/log:ro 
      - /var/run/docker.sock:/var/run/docker.sock:ro 
      - /var/lib/docker/containers:/var/lib/docker/containers:ro 
      - ./infra/promtail/config.yml:/etc/promtail/config.yml:ro
    depends_on: 
      - loki 
    restart: unless-stopped

    # ----- databases -----
  auth-users-db:  # auth + users postgres-healthcheck 
    <<: *x-postgres-healthcheck
    image: postgres:16
    container_name: auth-users-db 
    env_file: ./infra/env/.auth_users_db.env 
    ports: ["5433:5432"]
    volumes: 
      - pgdata-auth-users:/var/lib/postgresql/data 

  orders-payments-db:  # orders + payments postgres-healthcheck
    <<: [*x-postgres-healthcheck]
    image: postgres:16
    container_name: orders-payments-db 
    env_file: ./infra/env/.orders_payments_db.env 
    ports: ["5434:5432"]
    volumes:
      - pgdata-orders-payments:/var/lib/postgresql/data 

  catalog-db:
    <<: [*x-postgres-healthcheck]
    image: postgres:16
    container_name: catalog-db 
    env_file: ./infra/env/.catalog.env 
    ports: ["5435:5432"]
    volumes:
      - pgdata-catalog:/var/lib/postgresql/data 

  notifications-db:
    <<: [*x-postgres-healthcheck]
    image: postgres:16
    container_name: notifications-db
    env_file: ./infra/env/example.notifications_db.env
    ports: ["5436:5432"]
    volumes: 
      - pgdata-notifications:/var/lib/postgresql/data 

  # ----- services -----
  # auth:
  #   build: ./services/auth
  #   container_name: auth 
  #   env_file: ./infra/env/.auth.env 
  #   ports: ["8005:8080"]
  #   depends_on: 
  #     auth-users-db: { condition: service_healthy }
  #     redis: { condition: service_healthy }
  #     kafka: { condition: service_healthy }
  #
  users:
    build: ./services/users 
    container_name: users 
    env_file: ./infra/env/.users.env 
    ports: ["8001:8000"]
    depends_on:
      auth-users-db: { condition: service_healthy }
      kafka: { condition: service_healthy }

  catalog:
    container_name: catalog 
    build: ./services/catalog
    env_file: ./infra/env/.catalog.env 
    ports: ["8002:8000"]
    depends_on:
      catalog-db: { condition: service_healthy }
      kafka: { condition: service_healthy }

  orders:
    container_name: orders 
    build: ./services/orders 
    env_file: ./infra/env/.orders.env
    ports: ["8003:8000"]
    depends_on:
      orders-payments-db: { condition: service_healthy }
      kafka: {condition: service_healthy }
      # payments: { conditions: service_healthy }
  
  payments:
    container_name: payments
    build: ./services/payments 
    env_file: ./infra/env/.payments.env
    ports: ["8006:8080"]
    depends_on:
      orders-payments-db: { condition: service_healthy }
      redis: { condition: service_healthy }
      kafka: { condition: service_healthy }

  notifications: 
    container_name: notifications
    build: ./services/notifications 
    env_file: ./infra/env/.notifications.env 
    ports: ["8004:8000"]
    depends_on: 
      notifications-db: { condition: service_healthy }
      kafka: { condition: service_healthy }
      mailhog: { condition: service_started }
  #
  # recommendations:
  #   container_name: recommendations
  #   build: ./services/recommendations
  #   env_file: ./infra/env/.recommendation.env 
  #   ports: ["8007:8080"]
  #   depends_on:
  #     kafka: { condition: service_healthy }
  #

volumes:
  kafka-data:
  prometheus_data:
  grafana_data:
  loki_data:
  pgdata-auth-users:
  pgdata-orders-payments:
  pgdata-catalog:
  pgdata-notifications:



   
