global:
  scrape_interval: 15s
  scrape_timeout: 10s


scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]


  - job_name: services
    metrics_path: /metrics 
    static_configs:
      - targets: ["users:8000", "catalog:8000", "orders:8000"]
